### ISSUE TITLE
MQTT client, PubSubClient

### ISSUE THREAD

**Issue by Andrew-Wasserman** [Juerd/ESP-WiFiSettings#20]
Hi Jeud,

Is PubSubClient compatible with ESP-WiFiSettings? If so, could you perhaps share a very basic example?

**Comment by Juerd** [comment]
The annoying thing with PubSubClient is that it doesn't deal well with short lived arduino's String objects because they take a pointer and don't copy the string. That's why I use the library called MQTT from https://github.com/256dpi/arduino-mqtt

Some example projects with ESP-WiFiSetting and MQTT:
- https://github.com/revspace/operame
- https://github.com/revspace/extradoei
- https://github.com/revspace/spacevol
- https://github.com/Juerd/snuffelding
- https://github.com/Juerd/thermo
